[tools]
go = "latest"
node = "latest"

[dotfiles]
"~/.bin" = { mode = "track" }
"~/.config/mise" = { mode = "track" }
"~/.zshrc" = { mode = "track" }

[bootstrap.services.mise-history]
builtin = "history-watch"

[bootstrap.mise_shell_activate]
zprofile = "shims"    # good for non-interactive / Neovim
zshrc    = "activate" # full interactive activation

[bootstrap.packages]
"brew:ripgrep"     = "latest"
"brew:fd"          = "latest"
"brew:bat"         = "latest"
"brew:eza"         = "latest"
"brew:fzf"         = "latest"
"brew:zoxide"      = "latest"
"brew:jq"          = "latest"
"brew:gh"          = "latest"
"brew:lazygit"     = "latest"
"brew:neovim"      = "latest"
"brew:starship"    = "latest"
# "mas:497799835" = "latest"       # App Store apps (needs mas)

[bootstrap.macos.dock]
autohide = true
tilesize = 48

[bootstrap.macos.finder]
show_all_files = true
show_pathbar = true
