[tools]
go = "latest"
node = "latest"

[dotfiles]
"~/.bin" = { mode = "track" }
"~/.config/mise" = { mode = "track" }
"~/.zshrc" = { mode = "track" }

[bootstrap.services.mise-history]
builtin = "history-watch"

[bootstrap.mise_shell_activate]
zprofile = "shims"    # good for non-interactive / Neovim
zshrc    = "activate" # full interactive activation

[bootstrap.packages]
"brew:ripgrep"     = {os = ["macos"]}
"brew:fd"          = {os = ["macos"]}
"brew:bat"         = {os = ["macos"]}
"brew:eza"         = {os = ["macos"]}
"brew:fzf"         = {os = ["macos"]}
"brew:zoxide"      = {os = ["macos"]}
"brew:jq"          = {os = ["macos"]}
"brew:gh"          = {os = ["macos"]}
"brew:lazygit"     = {os = ["macos"]}
"brew:neovim"      = {os = ["macos"]}
"brew:starship"    = {os = ["macos"]}
"brew:tmux"        = {os = ["macos"]}
"brew:bottom"      = {os = ["macos"]}
"brew-cask:obsidian"    = {os = ["macos"]}

[bootstrap.macos.defaults]
"com.apple.finder" = {
  FXPreferredViewStyle = "Nlsv",          # explicit list view
  _FXSortFoldersFirst  = true
}

[bootstrap.macos.dock]
autohide = true
orientation = "bottom"
tilesize = 16
apps = [
	"/Applications/Ghostty.app",
	"/Applications/Safari.app",
]

[bootstrap.macos.finder]
show_all_files = true
show_pathbar = true
preferred_view_style = "list"

[bootstrap.macos.keyboard]
automatic_capitalization = false
automatic_spelling_correction = false

